// Generated by CoffeeScript 1.3.3
(function() {
  var $, SwitchImage, defaults, jQueryWidget, namespace;

  $ = jQuery;

  defaults = {
    selector: 'img',
    targetSelector: 'img',
    suffixes: {
      mouseover: '-on',
      mouseout: ''
    },
    animation: {
      on: {
        opacity: 1
      },
      off: {
        opacity: 0
      },
      duration: 600
    },
    easing: {
      on: 'easeOutQuad',
      off: 'easeInQuad'
    }
  };

  namespace = 'switchImage';

  $.fn[namespace] = {
    defaults: defaults
  };

  jQueryWidget = function(namespace, defaults, constructor) {
    return function(option) {
      var args;
      args = arguments;
      return this.each(function() {
        var $this, data, options;
        $this = $(this);
        data = $this.data(namespace);
        if (!data) {
          if (typeof option === 'object') {
            options = option;
          }
          if (options.animation) {
            options.animation = $.extend({}, defaults.animation, options.animation);
          }
          options = $.extend({}, defaults, options);
          $this.data(namespace, data = new constructor(this, options));
        }
        if (typeof option === 'string') {
          args = Array.prototype.slice.call(arguments, 0);
          args.shift();
          return data[option].apply(data, args);
        }
      });
    };
  };

  $.fn[namespace] = new jQueryWidget(namespace, defaults, SwitchImage = (function() {

    function SwitchImage(el, options) {
      var events, k, v, _ref;
      this.options = options;
      this.$el = $(el);
      events = [];
      _ref = this.options.suffixes;
      for (k in _ref) {
        v = _ref[k];
        events.push(k);
      }
      this.$el.find(this.options.selector).on(events.join(' '), $.proxy(this["switch"], this));
      this.klass = "" + namespace + "-switch";
      this.init();
    }

    SwitchImage.prototype.init = function() {
      var that;
      that = this;
      return this.$el.find(this.options.selector).each(function() {
        var $image, k, suffix, _ref, _results;
        $image = $(this).find(that.options.targetSelector);
        if (!($image.length > 0)) {
          return;
        }
        _ref = that.options.suffixes;
        _results = [];
        for (k in _ref) {
          suffix = _ref[k];
          if (suffix) {
            _results.push(that.loadSuffix(suffix, $image));
          } else {
            _results.push(void 0);
          }
        }
        return _results;
      });
    };

    SwitchImage.prototype.loadSuffix = function(suffix, $image) {
      var $switch, k, src, v, _ref;
      src = $image.attr('src').replace(/\./, suffix + ".");
      $image.css('z-index', 100);
      $switch = $("<img src='" + src + "' class='" + this.klass + "'>").css('zIndex', 0).css('position', 'absolute').css('top', 0).css('left', 0);
      if (this.options.animation) {
        _ref = this.options.animation.off;
        for (k in _ref) {
          v = _ref[k];
          $switch.css(k, v);
        }
      }
      $image.data(namespace, $switch);
      return $image.parent().css('position', 'relative').append($switch);
    };

    SwitchImage.prototype["switch"] = function(e) {
      var $el, $image, $switch, offset, suffix;
      suffix = this.options.suffixes[e.type];
      $el = $(e.currentTarget);
      if ($el.is(this.options.targetSelector)) {
        $image = $el;
      } else {
        $image = $el.find(this.options.targetSelector).not("." + this.klass);
      }
      if (!($image.length > 0)) {
        return;
      }
      if (e.type === 'mouseout') {
        offset = $image.offset();
        offset.right = offset.left + $image.width();
        offset.bottom = offset.top + $image.height();
        if (e.pageX >= offset.left && e.pageX <= offset.right && e.pageY >= offset.top && e.pageY <= offset.bottom) {
          return;
        }
      }
      $switch = $image.data(namespace);
      if ($switch && $image.width() && !$switch.css('width')) {
        $switch.width($image.width()).height($image.height());
      }
      return this.doSwitch(suffix, $image, $switch);
    };

    SwitchImage.prototype.doSwitch = function(suffix, $image, $switch) {
      var $off, $on, anim;
      if (suffix) {
        $on = $switch;
        $off = $image;
      } else {
        $on = $image;
        $off = $switch;
      }
      anim = this.options.animation;
      if (anim.duration) {
        $on.stop();
        if ($on) {
          $on.animate(anim.on, anim.duration, this.options.easing.on || this.options.easing);
        }
        $off.stop();
        if ($off) {
          return $off.animate(anim.off, anim.duration, this.options.easing.off || this.options.easing);
        }
      } else {
        if ($on) {
          $on.css(anim.on);
        }
        if ($off) {
          return $off.css(anim.off);
        }
      }
    };

    return SwitchImage;

  })());

}).call(this);
